name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # rama principal para despliegue

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Obtener el código fuente
    - name: Checkout repository
      uses: actions/checkout@v2

    # Paso 2: Iniciar sesión en Azure (usando el Service Principal)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Paso 3: Iniciar sesión en Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    # Paso 4: Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/billpredictor:${{ github.sha }} .

    # Paso 5: Subir la imagen a Azure Container Registry
    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/billpredictor:${{ github.sha }}

    # Paso 6: Desplegar en Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
        images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/billpredictor:${{ github.sha }}
        
